"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {useAuth} from "../../auth-provider";
import {supabase} from "../../supabase";

type Tab="overview"|"campaigns"|"calendar"|"creative"|"playbooks";
type Campaign={campaign_id:string;name:string;objective:string;hotel_codes:string[];hotel_label:string;booking_start:string;booking_end:string;stay_start:string;stay_end:string;campaign_type:string;direct_offer:string;direct_discount:number;ota_rule:string;fb_offer:string;value_add:string;revenue_guardrail:string;booking_channels:string;primary_kpis:string;status:string};
type Content={content_id:string;post_date:string;page_name:string;hotel_codes:string[];hotel_label:string;pillar:string;subject:string;campaign_linked:boolean;campaign_name:string|null;format:string;design_id:string;channels:string;design_status:string;approval_status:string;publish_status:string;notes:string|null};
type Creative={design_id:string;post_date:string;hotel_label:string;pillar:string;subject:string;headline:string;subheadline:string;asset_format:string;presentation_rule:string;status:string};
type CreativeDetail=Creative&{design_prompt:string;caption:string;hashtags:string;cta:string;page_name:string;campaign_name:string|null};
type Playbook={hotel_code:string;hotel_name:string;best_segments:string;strongest_periods:string;core_story:string;lead_events:string;cautions:string;best_channels:string;campaign_role:string;promotion_ideas:string;photography_priority:string;website_cta:string};
type Snapshot={hotel_code:string;stay_date:string;total_rooms:number;rooms_sold:number;available_rooms:number;occupancy_percent:number};

const HOTELS:Record<string,string>={GTL:"Grand Tamarind Lake",LTL:"Lavendish Tamarind Lifestyle",LWS:"Lavendish Wild Safari",LOH:"Lavendish Okrin Hotel",LLG:"Lavendish Lake Giritale",LBR:"Lavendish Beach Resort",LWW:"Lavendish Wild Wilpattu",MLR:"Miridiya Lake Resort",LCR:"Lavendish Country Resort",LHK:"Lavendish Hills Kandy"};
const WEEKDAYS=["MON","TUE","WED","THU","FRI","SAT","SUN"];
const fmt=(value:string,options?:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat("en-GB",options??{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${value}T00:00:00`));
const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const today=()=>iso(new Date());
const addDays=(value:string,days:number)=>{const date=new Date(`${value}T00:00:00`);date.setDate(date.getDate()+days);return iso(date)};
const statusLabel=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,letter=>letter.toUpperCase());

export function MarketingClient(){
 const {access,session}=useAuth();
 const [tab,setTab]=useState<Tab>("overview"),[campaigns,setCampaigns]=useState<Campaign[]>([]),[content,setContent]=useState<Content[]>([]),[creatives,setCreatives]=useState<Creative[]>([]),[playbooks,setPlaybooks]=useState<Playbook[]>([]),[snapshots,setSnapshots]=useState<Snapshot[]>([]);
 const [loading,setLoading]=useState(true),[message,setMessage]=useState(""),[hotel,setHotel]=useState("ALL"),[query,setQuery]=useState(""),[selectedCampaign,setSelectedCampaign]=useState<Campaign|null>(null),[selectedCreative,setSelectedCreative]=useState<CreativeDetail|null>(null),[selectedPlaybook,setSelectedPlaybook]=useState<Playbook|null>(null),[importing,setImporting]=useState(false),[copyNotice,setCopyNotice]=useState("");
 const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[selectedDate,setSelectedDate]=useState(today());
 const master=access?.role==="MASTER_ADMIN";
 const allowedCodes=useMemo(()=>access?.hotel_codes.includes("ALL")?Object.keys(HOTELS):Object.keys(HOTELS).filter(code=>access?.hotel_codes.includes(code)),[access]);

 const load=useCallback(async()=>{
  if(!session)return;setLoading(true);setMessage("");const from=today(),to=addDays(from,60);
  const [campaignResult,contentResult,creativeResult,playbookResult,snapshotResult]=await Promise.all([
   supabase.from("marketing_campaigns").select("*").order("booking_start"),
   supabase.from("marketing_content").select("content_id,post_date,page_name,hotel_codes,hotel_label,pillar,subject,campaign_linked,campaign_name,format,design_id,channels,design_status,approval_status,publish_status,notes").order("post_date"),
   supabase.from("marketing_creatives").select("design_id,post_date,hotel_label,pillar,subject,headline,subheadline,asset_format,presentation_rule,status").order("post_date"),
   supabase.from("marketing_hotel_playbooks").select("*").order("hotel_name"),
   supabase.from("yield_occupancy_snapshots").select("hotel_code,stay_date,total_rooms,rooms_sold,available_rooms,occupancy_percent").gte("stay_date",from).lte("stay_date",to).order("stay_date")
  ]);
  const error=campaignResult.error||contentResult.error||creativeResult.error||playbookResult.error||snapshotResult.error;
  if(error)setMessage(error.message);else{setCampaigns((campaignResult.data??[]) as Campaign[]);setContent((contentResult.data??[]) as Content[]);setCreatives((creativeResult.data??[]) as Creative[]);setPlaybooks((playbookResult.data??[]) as Playbook[]);setSnapshots((snapshotResult.data??[]) as Snapshot[])}setLoading(false)
 },[session]);
 // Initial remote synchronization is intentionally started when auth becomes available.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[load]);

 async function importPlan(){if(!session||!master)return;setImporting(true);setMessage("");try{const response=await fetch("/api/admin/marketing/import",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`}}),result=await response.json();if(!response.ok)throw new Error(result.error??"Import failed");setMessage(`Master plan loaded: ${result.counts.campaigns} campaigns, ${result.counts.content} content items and ${result.counts.creatives} creatives.`);await load()}catch(error){setMessage(error instanceof Error?error.message:"Import failed")}finally{setImporting(false)}}
 async function updateContent(item:Content,patch:Partial<Content>){if(!session)return;const next={...patch,updated_by:session.user.id,updated_at:new Date().toISOString()};const {error}=await supabase.from("marketing_content").update(next).eq("content_id",item.content_id);if(error){setMessage(error.message);return}setContent(current=>current.map(row=>row.content_id===item.content_id?{...row,...patch}:row))}
 async function openCreative(item:Creative){setSelectedCreative(null);const {data,error}=await supabase.from("marketing_creatives").select("*").eq("design_id",item.design_id).single();if(error)setMessage(error.message);else setSelectedCreative(data as CreativeDetail)}
 async function copy(value:string,label:string){await navigator.clipboard.writeText(value||"");setCopyNotice(`${label} copied`);window.setTimeout(()=>setCopyNotice(""),2200)}

 const priorities=useMemo(()=>allowedCodes.map(code=>{const rows=snapshots.filter(row=>row.hotel_code===code&&row.stay_date<=addDays(today(),30));const avg=rows.length?Math.round(rows.reduce((sum,row)=>sum+Number(row.occupancy_percent),0)/rows.length):null;const low=rows.filter(row=>Number(row.occupancy_percent)<45).length;const posts=content.filter(item=>item.post_date>=today()&&item.post_date<=addDays(today(),14)&&item.hotel_codes.includes(code));const playbook=playbooks.find(item=>item.hotel_code===code);return{code,name:HOTELS[code],avg,low,posts,playbook,level:avg===null?"missing":avg<35?"urgent":avg<55?"attention":"healthy"}}).sort((a,b)=>(a.avg??101)-(b.avg??101)),[allowedCodes,content,playbooks,snapshots]);
 const upcomingCampaigns=useMemo(()=>campaigns.filter(item=>item.booking_end>=today()).filter(item=>hotel==="ALL"||item.hotel_codes.includes(hotel)),[campaigns,hotel]);
 const dueContent=useMemo(()=>content.filter(item=>item.post_date>=today()&&item.post_date<=addDays(today(),14)),[content]);
 const overdue=useMemo(()=>content.filter(item=>item.post_date<today()&&item.publish_status!=="PUBLISHED"),[content]);
 const filteredContent=useMemo(()=>content.filter(item=>(hotel==="ALL"||item.hotel_codes.includes(hotel))&&(!query||`${item.content_id} ${item.subject} ${item.pillar} ${item.campaign_name??""}`.toLowerCase().includes(query.toLowerCase()))),[content,hotel,query]);
 const filteredCreatives=useMemo(()=>creatives.filter(item=>(hotel==="ALL"||item.hotel_label.toLowerCase().includes((HOTELS[hotel]??"").toLowerCase()))&&(!query||`${item.design_id} ${item.subject} ${item.headline}`.toLowerCase().includes(query.toLowerCase()))),[creatives,hotel,query]);
 const monthStart=new Date(month.getFullYear(),month.getMonth(),1),days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),offset=(monthStart.getDay()+6)%7;
 const calendarCells=Array.from({length:Math.ceil((offset+days)/7)*7},(_,index)=>{const day=index-offset+1;return day>=1&&day<=days?day:null});
 const calendarItems=filteredContent.filter(item=>{const date=new Date(`${item.post_date}T00:00:00`);return date.getFullYear()===month.getFullYear()&&date.getMonth()===month.getMonth()});
 const selectedItems=calendarItems.filter(item=>item.post_date===selectedDate);
 const menu:[Tab,string,string][]=[["overview","Command centre","Priorities"],["campaigns","Campaigns","28-plan"],["calendar","Content calendar","351 posts"],["creative","Creative library","Prompts"],["playbooks","Hotel playbooks","10 hotels"]];

 return <div className="marketing-page">
  <section className="marketing-hero"><div><span>15 AUG 2026 — 31 AUG 2027</span><h2>Marketing Command Centre</h2><p>Campaign planning, content production and hotel-specific action—prioritised by live occupancy.</p></div><div className="marketing-hero-actions"><label>Hotel<select value={hotel} onChange={event=>setHotel(event.target.value)}><option value="ALL">All permitted hotels</option>{allowedCodes.map(code=><option value={code} key={code}>{HOTELS[code]}</option>)}</select></label>{master&&<button onClick={()=>void importPlan()} disabled={importing}>{importing?"Loading plan...":campaigns.length?"Refresh master plan":"Load master plan"}</button>}</div></section>
  {message&&<div className={`marketing-message ${message.includes("loaded")?"success":""}`}>{message}</div>}
  <nav className="marketing-tabs" aria-label="Marketing sections">{menu.map(([key,label,small])=><button className={tab===key?"active":""} onClick={()=>setTab(key)} key={key}><b>{label}</b><span>{small}</span></button>)}</nav>
  {loading?<div className="marketing-empty"><b>Opening the marketing plan...</b><span>Campaigns, content and occupancy signals are being connected.</span></div>:!campaigns.length?<div className="marketing-empty"><b>Master plan ready to import</b><span>Run the marketing SQL in Supabase, then use Load master plan once.</span>{master&&<button onClick={()=>void importPlan()} disabled={importing}>Load 2026–2027 plan</button>}</div>:<>
   {tab==="overview"&&<div className="marketing-overview"><section className="marketing-kpis"><article><span>LIVE / UPCOMING CAMPAIGNS</span><b>{upcomingCampaigns.length}</b><small>{campaigns.length} in master plan</small></article><article><span>CONTENT DUE — 14 DAYS</span><b>{dueContent.length}</b><small>{dueContent.filter(item=>item.design_status==="NOT_STARTED").length} designs not started</small></article><article className={overdue.length?"warning":""}><span>OVERDUE ITEMS</span><b>{overdue.length}</b><small>Not marked published</small></article><article><span>HOTELS NEEDING DEMAND</span><b>{priorities.filter(item=>item.level==="urgent").length}</b><small>Below 35% next-30-day average</small></article></section><section className="marketing-grid"><div className="marketing-panel occupancy-priority"><header><div><h3>Occupancy-led priorities</h3><p>Fast Supabase snapshots · next 30 stay days</p></div><span>LIVE CONNECTION</span></header><div>{priorities.map(item=><button onClick={()=>{setHotel(item.code);setTab("calendar")}} className={item.level} key={item.code}><span>{item.code}</span><div><b>{item.name}</b><small>{item.avg===null?"No saved occupancy data":`${item.low} low-occupancy dates · ${item.posts.length} posts due`}</small></div><strong>{item.avg===null?"—":`${item.avg}%`}</strong></button>)}</div></div><div className="marketing-panel next-actions"><header><div><h3>Next marketing actions</h3><p>What the team should prepare now</p></div></header><div>{dueContent.slice(0,8).map(item=><article key={item.content_id}><time>{fmt(item.post_date,{day:"numeric",month:"short"})}</time><div><b>{item.subject}</b><small>{item.hotel_label} · {statusLabel(item.design_status)}</small></div><button onClick={()=>{setSelectedDate(item.post_date);setMonth(new Date(`${item.post_date}T00:00:00`));setTab("calendar")}}>Open</button></article>)}</div></div></section></div>}
   {tab==="campaigns"&&<section className="marketing-list-view"><header><div><h3>Commercial campaign calendar</h3><p>Offer, booking window, stay period and revenue guardrails.</p></div><span>{upcomingCampaigns.length} visible</span></header><div className="campaign-list">{upcomingCampaigns.map(item=><button key={item.campaign_id} onClick={()=>setSelectedCampaign(item)}><span className="campaign-id">{item.campaign_id}</span><div><b>{item.name}</b><small>{item.hotel_label}</small></div><time><b>{fmt(item.booking_start,{day:"numeric",month:"short"})} — {fmt(item.booking_end,{day:"numeric",month:"short"})}</b><small>Booking window</small></time><em>{statusLabel(item.status)}</em></button>)}</div></section>}
   {tab==="calendar"&&<section className="marketing-calendar-view"><header><div><h3>Content calendar</h3><p>Click a date to review and update scheduled content.</p></div><div><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><b>{new Intl.DateTimeFormat("en-GB",{month:"long",year:"numeric"}).format(month)}</b><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div></header><div className="marketing-calendar-layout"><div className="marketing-calendar"><div className="weekday-row">{WEEKDAYS.map(day=><span key={day}>{day}</span>)}</div><div className="calendar-grid">{calendarCells.map((day,index)=>{const date=day?iso(new Date(month.getFullYear(),month.getMonth(),day)):"";const items=day?calendarItems.filter(item=>item.post_date===date):[];return <button disabled={!day} className={`${date===selectedDate?"selected":""} ${date===today()?"today":""}`} onClick={()=>setSelectedDate(date)} key={index}>{day&&<><span>{day}</span>{items.slice(0,2).map(item=><small key={item.content_id}>{item.content_id} · {item.pillar}</small>)}{items.length>2&&<em>+{items.length-2} more</em>}</>}</button>})}</div></div><aside className="day-content"><header><span>SELECTED DATE</span><h3>{selectedDate?fmt(selectedDate):"Choose a date"}</h3><small>{selectedItems.length} scheduled items</small></header><div>{selectedItems.map(item=><article key={item.content_id}><div><span>{item.content_id}</span><em>{item.pillar}</em></div><b>{item.subject}</b><small>{item.hotel_label}</small><footer><button onClick={()=>void updateContent(item,{design_status:"COMPLETED"})}>{item.design_status==="COMPLETED"?"Designed":"Mark designed"}</button><button onClick={()=>void updateContent(item,{approval_status:"APPROVED"})}>{item.approval_status==="APPROVED"?"Approved":"Approve"}</button><button onClick={()=>void updateContent(item,{publish_status:"PUBLISHED"})}>{item.publish_status==="PUBLISHED"?"Published":"Mark published"}</button></footer></article>)}{!selectedItems.length&&<p className="no-day-items">No content scheduled for this date.</p>}</div></aside></div></section>}
   {tab==="creative"&&<section className="marketing-list-view"><header><div><h3>Design & caption library</h3><p>Complete prompts, captions, hashtags and verified-asset rules.</p></div><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search designs..."/></header><div className="creative-grid">{filteredCreatives.map(item=><button onClick={()=>void openCreative(item)} key={item.design_id}><span>{item.design_id}</span><b>{item.headline||item.subject}</b><small>{item.hotel_label} · {item.asset_format}</small><em>{statusLabel(item.status)}</em></button>)}</div></section>}
   {tab==="playbooks"&&<section className="marketing-list-view"><header><div><h3>Hotel marketing playbooks</h3><p>Positioning and presentation rules for every property.</p></div></header><div className="playbook-grid">{playbooks.filter(item=>hotel==="ALL"||item.hotel_code===hotel).map(item=><button onClick={()=>setSelectedPlaybook(item)} key={item.hotel_code}><span>{item.hotel_code}</span><div><b>{HOTELS[item.hotel_code]??item.hotel_name}</b><small>{item.core_story}</small></div><em>{item.strongest_periods}</em></button>)}</div></section>}
  </>}
  {selectedCampaign&&<div className="marketing-modal-backdrop" onClick={event=>event.currentTarget===event.target&&setSelectedCampaign(null)}><section className="marketing-modal"><button className="modal-close" onClick={()=>setSelectedCampaign(null)}>×</button><span>{selectedCampaign.campaign_id} · {selectedCampaign.campaign_type}</span><h2>{selectedCampaign.name}</h2><p>{selectedCampaign.objective}</p><dl><div><dt>Booking window</dt><dd>{fmt(selectedCampaign.booking_start)} — {fmt(selectedCampaign.booking_end)}</dd></div><div><dt>Stay period</dt><dd>{fmt(selectedCampaign.stay_start)} — {fmt(selectedCampaign.stay_end)}</dd></div><div><dt>Hotels</dt><dd>{selectedCampaign.hotel_label}</dd></div><div><dt>Direct offer</dt><dd>{selectedCampaign.direct_offer}</dd></div><div><dt>OTA rule</dt><dd>{selectedCampaign.ota_rule}</dd></div><div><dt>F&amp;B</dt><dd>{selectedCampaign.fb_offer}</dd></div><div><dt>Value-add</dt><dd>{selectedCampaign.value_add}</dd></div><div><dt>Revenue guardrail</dt><dd>{selectedCampaign.revenue_guardrail}</dd></div></dl></section></div>}
  {selectedCreative&&<div className="marketing-modal-backdrop" onClick={event=>event.currentTarget===event.target&&setSelectedCreative(null)}><section className="marketing-modal creative-modal"><button className="modal-close" onClick={()=>setSelectedCreative(null)}>×</button><span>{selectedCreative.design_id} · {selectedCreative.pillar}</span><h2>{selectedCreative.headline}</h2><p>{selectedCreative.subheadline}</p><div className="creative-block"><header><b>Complete design prompt</b><button onClick={()=>void copy(selectedCreative.design_prompt,"Design prompt")}>Copy</button></header><pre>{selectedCreative.design_prompt}</pre></div><div className="creative-block"><header><b>Final caption</b><button onClick={()=>void copy(selectedCreative.caption,"Caption")}>Copy</button></header><p>{selectedCreative.caption}</p></div><div className="creative-block compact"><b>{selectedCreative.hashtags}</b><button onClick={()=>void copy(selectedCreative.hashtags,"Hashtags")}>Copy hashtags</button></div></section></div>}
  {selectedPlaybook&&<div className="marketing-modal-backdrop" onClick={event=>event.currentTarget===event.target&&setSelectedPlaybook(null)}><section className="marketing-modal"><button className="modal-close" onClick={()=>setSelectedPlaybook(null)}>×</button><span>{selectedPlaybook.hotel_code} · HOTEL PLAYBOOK</span><h2>{HOTELS[selectedPlaybook.hotel_code]??selectedPlaybook.hotel_name}</h2><p>{selectedPlaybook.core_story}</p><dl><div><dt>Best-fit segments</dt><dd>{selectedPlaybook.best_segments}</dd></div><div><dt>Strongest periods</dt><dd>{selectedPlaybook.strongest_periods}</dd></div><div><dt>Lead events</dt><dd>{selectedPlaybook.lead_events}</dd></div><div><dt>Best channels</dt><dd>{selectedPlaybook.best_channels}</dd></div><div><dt>Promotion ideas</dt><dd>{selectedPlaybook.promotion_ideas}</dd></div><div><dt>Photography priority</dt><dd>{selectedPlaybook.photography_priority}</dd></div><div><dt>Important cautions</dt><dd>{selectedPlaybook.cautions}</dd></div></dl></section></div>}
  {copyNotice&&<div className="marketing-copy-notice">{copyNotice}</div>}
 </div>
}
