export type HotelData = {
  code: string;
  name: string;
  shortName: string;
  location: string;
  rooms: number;
  updated: string;
  updatedState: "current" | "old";
  occupied: number[];
  sources: {
    name: string;
    rooms: number;
    group: "agent" | "ota" | "direct" | "other";
    daily?: number[];
  }[];
  functions: number;
  allotment: number;
};
const S = (
  name: string,
  rooms: number,
  group: HotelData["sources"][number]["group"],
) => ({ name, rooms, group });
const imported = "Imported from July 2026 sheet";

export const hotels: HotelData[] = [
  {
    code: "MLR",
    name: "Miridiya Lake Resort",
    shortName: "Miridiya Lake Resort",
    location: "Anuradhapura",
    rooms: 38,
    updated: imported,
    updatedState: "current",
    occupied: [
      10, 7, 6, 8, 19, 21, 11, 7, 8, 10, 31, 12, 8, 8, 6, 11, 17, 31, 35, 18,
      14, 2, 21, 22, 30, 20, 15, 19, 6, 11, 7,
    ],
    sources: [
      S("Travel Agent - LLHR", 137, "agent"),
      S("Travel Agent - EH", 58, "agent"),
      S("Booking.com", 73, "ota"),
      S("Agoda", 2, "ota"),
      S("Expedia", 3, "ota"),
      S("Trip.com", 24, "ota"),
      S("Website Exely", 17, "direct"),
      S("Pioosa Leisure", 9, "agent"),
      S("FIT - Local", 103, "direct"),
      S("FIT - Foreign", 18, "direct"),
      S("FOC", 7, "other"),
    ],
    functions: 0,
    allotment: 0,
  },
  {
    code: "GTL",
    name: "Grand Tamarind Lake",
    shortName: "Grand Tamarind Lake",
    location: "Kataragama",
    rooms: 25,
    updated: imported,
    updatedState: "current",
    occupied: [
      9, 9, 15, 20, 10, 12, 18, 22, 19, 25, 21, 2, 14, 18, 16, 16, 17, 22, 20,
      11, 13, 7, 9, 22, 13, 18, 12, 22, 23, 9, 8,
    ],
    sources: [
      S("Travel Agent - LLHR", 54, "agent"),
      S("Travel Agent - EH", 23, "agent"),
      S("Booking.com", 115, "ota"),
      S("Trip.com", 9, "ota"),
      S("Website Exely", 17, "direct"),
      S("Pioosa Leisure", 1, "agent"),
      S("FIT - Local", 228, "direct"),
      S("FOC", 30, "other"),
    ],
    functions: 0,
    allotment: 0,
  },
  {
    code: "LOH",
    name: "Lavendish Okrin Hotel",
    shortName: "Lavendish Okrin Hotel",
    location: "Kataragama",
    rooms: 17,
    updated: imported,
    updatedState: "current",
    occupied: [
      2, 3, 2, 9, 3, 2, 7, 4, 3, 9, 15, 4, 6, 6, 7, 5, 7, 8, 13, 9, 6, 4, 0, 4,
      4, 15, 14, 14, 14, 17, 3,
    ],
    sources: [
      S("Travel Agent - LLHR", 50, "agent"),
      S("Booking.com", 45, "ota"),
      S("Agoda", 4, "ota"),
      S("Expedia", 2, "ota"),
      S("Website Exely", 4, "direct"),
      S("Pioosa Leisure", 1, "agent"),
      S("Fantastic Traveller", 3, "agent"),
      S("FIT - Local", 105, "direct"),
      S("FOC", 5, "other"),
    ],
    functions: 0,
    allotment: 0,
  },
  {
    code: "LWS",
    name: "Lavendish Wild Safari",
    shortName: "Lavendish Wild Safari",
    location: "Wasgamuwa",
    rooms: 27,
    updated: imported,
    updatedState: "current",
    occupied: [
      2, 2, 23, 0, 0, 5, 4, 4, 6, 3, 26, 1, 4, 12, 6, 7, 9, 16, 2, 7, 5, 2, 2,
      1, 13, 7, 15, 17, 3, 11, 5,
    ],
    sources: [
      S("Travel Agent - LLHR", 55, "agent"),
      S("Travel Agent - EH", 4, "agent"),
      S("Booking.com", 31, "ota"),
      S("Website Exely", 8, "direct"),
      S("FIT - Local", 61, "direct"),
      S("FIT - Foreign", 59, "direct"),
      S("Pioosa Leisure", 1, "agent"),
      S("FOC", 1, "other"),
    ],
    functions: 0,
    allotment: 0,
  },
  {
    code: "LWW",
    name: "Lavendish Wild Wilpattu",
    shortName: "Lavendish Wild Wilpattu",
    location: "Wilpattu",
    rooms: 12,
    updated: imported,
    updatedState: "current",
    occupied: [
      4, 6, 3, 11, 2, 7, 6, 5, 5, 7, 11, 3, 3, 6, 8, 11, 10, 10, 8, 3, 10, 8, 2,
      10, 7, 8, 10, 1, 0, 4, 3,
    ],
    sources: [
      S("Travel Agent - LLHR", 38, "agent"),
      S("Travel Agent - EH", 2, "agent"),
      S("Booking.com", 93, "ota"),
      S("Website Exely", 5, "direct"),
      S("Fantastic Travelers", 2, "agent"),
      S("FIT - Local", 43, "direct"),
      S("FIT - Foreign", 5, "direct"),
      S("FOC", 4, "other"),
    ],
    functions: 0,
    allotment: 0,
  },
  {
    code: "LCR",
    name: "Lavendish Country Resort",
    shortName: "Lavendish Country Resort",
    location: "Dambulla",
    rooms: 18,
    updated: imported,
    updatedState: "current",
    occupied: [
      0, 0, 9, 3, 0, 0, 4, 1, 0, 16, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 16, 16, 2, 0,
      15, 0, 0, 0, 0, 2, 13,
    ],
    sources: [
      S("Booking.com", 5, "ota"),
      S("Pioosa Leisure", 15, "agent"),
      S("Fantastic Traveller", 15, "agent"),
      S("FIT - Local", 66, "direct"),
      S("FOC", 1, "other"),
    ],
    functions: 0,
    allotment: 0,
  },
  {
    code: "LLG",
    name: "Lavendish Lake Giritale",
    shortName: "Lavendish Lake Giritale",
    location: "Giritale",
    rooms: 42,
    updated: imported,
    updatedState: "current",
    occupied: [
      6, 4, 3, 11, 4, 3, 5, 12, 9, 41, 42, 36, 30, 4, 12, 17, 31, 36, 6, 1, 20,
      24, 17, 13, 0, 17, 13, 0, 27, 23, 28,
    ],
    sources: [
      S("Travel Agent - LLHR", 257, "agent"),
      S("Travel Agent - EH", 1, "agent"),
      S("Booking.com", 25, "ota"),
      S("Agoda", 5, "ota"),
      S("Website Exely", 1, "direct"),
      S("FIT - Local", 177, "direct"),
      S("FIT - Foreign", 12, "direct"),
      S("FOC", 17, "other"),
    ],
    functions: 0,
    allotment: 0,
  },
  {
    code: "LHK",
    name: "Lavendish Hills Kandy",
    shortName: "Lavendish Hills Kandy",
    location: "Kandy",
    rooms: 43,
    updated: imported,
    updatedState: "current",
    occupied: [
      7, 16, 5, 11, 13, 5, 9, 5, 4, 11, 8, 12, 13, 4, 4, 6, 14, 8, 13, 1, 5, 22,
      7, 24, 27, 31, 2, 6, 1, 30, 30,
    ],
    sources: [
      S("Travel Agent - LLHR", 294, "agent"),
      S("Booking.com", 13, "ota"),
      S("Pioosa Leisure", 3, "agent"),
      S("FIT - Local", 30, "direct"),
      S("FIT - Foreign", 5, "direct"),
      S("FOC", 9, "other"),
    ],
    functions: 0,
    allotment: 0,
  },
  {
    code: "LTL",
    name: "Lavendish Tamarind Lifestyle",
    shortName: "Lavendish Tamarind Lifestyle",
    location: "Kataragama",
    rooms: 17,
    updated: imported,
    updatedState: "current",
    occupied: [
      6, 10, 11, 14, 9, 4, 8, 8, 2, 13, 15, 4, 7, 4, 2, 2, 11, 14, 9, 16, 4, 10,
      2, 9, 16, 16, 4, 15, 16, 2, 2,
    ],
    sources: [
      S("Travel Agent", 19, "agent"),
      S("EH Other", 19, "agent"),
      S("Booking.com", 66, "ota"),
      S("Agoda", 13, "ota"),
      S("Expedia", 8, "ota"),
      S("Website Exely", 25, "direct"),
      S("FIT - Local", 115, "direct"),
    ],
    functions: 0,
    allotment: 0,
  },
  {
    code: "LBR",
    name: "Lavendish Beach Resort",
    shortName: "Lavendish Beach Resort",
    location: "Unawatuna",
    rooms: 40,
    updated: imported,
    updatedState: "current",
    occupied: [
      20, 20, 19, 1, 0, 0, 3, 2, 4, 3, 4, 2, 9, 10, 0, 1, 3, 10, 11, 8, 4, 1, 1,
      2, 0, 9, 22, 24, 0, 0, 0,
    ],
    sources: [
      S("Travel Agent - LLHR", 5, "agent"),
      S("Travel Agent - EH", 97, "agent"),
      S("Booking.com", 10, "ota"),
      S("Trip.com", 10, "ota"),
      S("Pioosa Leisure", 1, "agent"),
      S("Fantastic Travelers", 3, "agent"),
      S("FIT - Local", 7, "direct"),
      S("FIT - Foreign", 58, "direct"),
      S("FOC", 2, "other"),
    ],
    functions: 0,
    allotment: 3,
  },
];
export const weekdays = [
  "Wed",
  "Thu",
  "Fri",
  "Sat",
  "Sun",
  "Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "Sat",
  "Sun",
  "Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "Sat",
  "Sun",
  "Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "Sat",
  "Sun",
  "Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
];
