import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";

const SUPABASE_URL="https://otiiioaazkanroyzvlkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_zMueiaaAsayg8y1fOBazLg_MauoW5hY";
const ROLES=["MASTER_ADMIN","HEAD_OFFICE","GM","NKH_STAFF","VIEWER"] as const;
const HOTEL_CODES=["GTL","LTL","LWS","LOH","LLG","LBR","LWW","MLR","LCR","LHK"];
const PAGE_CODES=["HOTEL_OCCUPANCY","GROUP_OCCUPANCY","OTA_ALERTS","YIELD_ALERTS","COMP_SET","TASKS","MARKETING","PROPERTIES","REPUTATION","REPORTS","SETTINGS"];
const MARKETING_SECTION_CODES=["MARKETING_OVERVIEW","MARKETING_CAMPAIGNS","MARKETING_CALENDAR","MARKETING_CREATIVES","MARKETING_PLAYBOOKS","MARKETING_UPDATE_STATUS","MARKETING_EDIT_PLANS"];

function adminClient(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY??process.env.SUPABASE_SECRET_KEY;if(!key)throw new Error("SUPABASE_SERVICE_ROLE_KEY is not configured");return createClient(SUPABASE_URL,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function requireMasterAdmin(request:NextRequest){const authorization=request.headers.get("authorization")??"";const token=authorization.startsWith("Bearer ")?authorization.slice(7):"";if(!token)return {error:NextResponse.json({error:"Authentication required"},{status:401}),user:null};const client=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error}=await client.auth.getUser(token);if(error||!user)return {error:NextResponse.json({error:"Invalid session"},{status:401}),user:null};const {data:access}=await adminClient().from("occupancy_user_access").select("role,active").eq("user_id",user.id).maybeSingle();if(!access?.active||access.role!=="MASTER_ADMIN")return {error:NextResponse.json({error:"Master Admin access required"},{status:403}),user:null};return {user,error:null}}
function validHotels(value:unknown):value is string[]{return Array.isArray(value)&&value.length>0&&(value.includes("ALL")?value.length===1:value.every(code=>HOTEL_CODES.includes(String(code))))}
function validPages(value:unknown):value is string[]{return Array.isArray(value)&&value.length>0&&(value.includes("ALL")?value.length===1:value.every(code=>PAGE_CODES.includes(String(code))))}
function validMarketingSections(value:unknown):value is string[]{return Array.isArray(value)&&(value.includes("ALL")?value.length===1:value.every(code=>MARKETING_SECTION_CODES.includes(String(code))))}

export async function GET(request:NextRequest){
 const auth=await requireMasterAdmin(request);if(auth.error)return auth.error;
 try{const admin=adminClient();const {data:authData,error:authError}=await admin.auth.admin.listUsers({page:1,perPage:1000});if(authError)throw authError;
  const {data:rows,error:accessError}=await admin.from("occupancy_user_access").select("user_id,role,hotel_codes,page_codes,marketing_section_codes,active");if(accessError)throw accessError;
  const byUser=new Map((rows??[]).map(row=>[row.user_id,row]));
  const users=authData.users.map(user=>{const access=byUser.get(user.id);return{id:user.id,name:String(user.user_metadata?.full_name??user.user_metadata?.name??user.email?.split("@")[0]??"User"),email:user.email??"",role:access?.role??"VIEWER",hotels:access?.hotel_codes??[],pages:access?.page_codes??(access?.role==="MASTER_ADMIN"?["ALL"]:["HOTEL_OCCUPANCY"]),marketingSections:access?.marketing_section_codes??(access?.role==="MASTER_ADMIN"?["ALL"]:[]),active:access?.active??false,createdAt:user.created_at,lastSignInAt:user.last_sign_in_at??null}}).sort((a,b)=>a.name.localeCompare(b.name));
  return NextResponse.json({users});
 }catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not load users"},{status:500})}
}

type UserBody={id?:string;name?:string;email?:string;password?:string;role?:string;hotels?:string[];pages?:string[];marketingSections?:string[];active?:boolean};
function validate(body:UserBody,editing=false){const password=String(body.password??"");return String(body.name??"").trim().length>=2&&String(body.email??"").includes("@")&&(!editing?password.length>=8:!password||password.length>=8)&&ROLES.includes(String(body.role??"") as typeof ROLES[number])&&validHotels(body.hotels)&&validPages(body.pages)&&validMarketingSections(body.marketingSections)}
function permissions(body:UserBody){const master=body.role==="MASTER_ADMIN";const marketingEnabled=master||body.pages?.includes("ALL")||body.pages?.includes("MARKETING");return{pages:master?["ALL"]:body.pages,marketingSections:master?["ALL"]:marketingEnabled?body.marketingSections:[]}}

export async function POST(request:NextRequest){const auth=await requireMasterAdmin(request);if(auth.error)return auth.error;try{const body=await request.json() as UserBody;if(!validate(body))return NextResponse.json({error:"Complete all required fields, hotel, page and Marketing access. Password must contain at least 8 characters."},{status:400});const name=String(body.name).trim(),email=String(body.email).trim().toLowerCase(),role=String(body.role),admin=adminClient();const {data,error:createError}=await admin.auth.admin.createUser({email,password:String(body.password),email_confirm:true,user_metadata:{full_name:name}});if(createError||!data.user)throw createError??new Error("User was not created");const access=permissions(body);const {error:accessError}=await admin.from("occupancy_user_access").insert({user_id:data.user.id,role,hotel_codes:body.hotels,page_codes:access.pages,marketing_section_codes:access.marketingSections,active:body.active!==false});if(accessError){await admin.auth.admin.deleteUser(data.user.id);throw accessError}return NextResponse.json({user:{id:data.user.id,name,email,role,hotels:body.hotels,pages:access.pages,marketingSections:access.marketingSections,active:body.active!==false}},{status:201})}catch(error){const message=error instanceof Error?error.message:"Could not create user";return NextResponse.json({error:/already|registered/i.test(message)?"A user with this email already exists.":message},{status:400})}}

export async function PATCH(request:NextRequest){const auth=await requireMasterAdmin(request);if(auth.error)return auth.error;try{const body=await request.json() as UserBody;if(!body.id||!validate(body,true))return NextResponse.json({error:"Check the details, hotel, page and Marketing section access. A new password must contain at least 8 characters."},{status:400});const id=String(body.id),name=String(body.name).trim(),email=String(body.email).trim().toLowerCase(),role=String(body.role);if(id===auth.user?.id&&(role!=="MASTER_ADMIN"||body.active===false))return NextResponse.json({error:"You cannot remove your own Master Admin access."},{status:400});const admin=adminClient();const attributes:{email:string;user_metadata:{full_name:string};password?:string}={email,user_metadata:{full_name:name}};if(body.password)attributes.password=String(body.password);const {error:updateError}=await admin.auth.admin.updateUserById(id,attributes);if(updateError)throw updateError;const access=permissions(body);const {error:accessError}=await admin.from("occupancy_user_access").upsert({user_id:id,role,hotel_codes:body.hotels,page_codes:access.pages,marketing_section_codes:access.marketingSections,active:body.active!==false},{onConflict:"user_id"});if(accessError)throw accessError;return NextResponse.json({user:{id,name,email,role,hotels:body.hotels,pages:access.pages,marketingSections:access.marketingSections,active:body.active!==false}})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not update user"},{status:400})}}
