import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";

export const dynamic="force-dynamic";
const SUPABASE_URL="https://otiiioaazkanroyzvlkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_zMueiaaAsayg8y1fOBazLg_MauoW5hY";
function adminClient(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY??process.env.SUPABASE_SECRET_KEY;if(!key)throw new Error("SUPABASE_SERVICE_ROLE_KEY is not configured");return createClient(SUPABASE_URL,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function requireMaster(request:NextRequest){const token=(request.headers.get("authorization")??"").replace(/^Bearer /,"");if(!token)return null;const auth=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});const {data:{user}}=await auth.auth.getUser(token);if(!user)return null;const {data}=await adminClient().from("occupancy_user_access").select("role,active").eq("user_id",user.id).maybeSingle();return data?.active&&data.role==="MASTER_ADMIN"?user:null}
type Competitor={name:string;url:string;active:boolean};
function clean(list:unknown,limit:number){return (Array.isArray(list)?list:[]).slice(0,limit).map(item=>{const value=item as Partial<Competitor>;return {name:String(value.name??"").trim(),url:String(value.url??"").trim(),active:value.active!==false}}).filter(item=>item.name)}
export async function POST(request:NextRequest){try{const user=await requireMaster(request);if(!user)return NextResponse.json({error:"Master Admin access required"},{status:403});const body=await request.json() as {propertyId?:string;competitorSet?:{main?:unknown;additional?:unknown;criteria?:Record<string,unknown>}};if(!body.propertyId)return NextResponse.json({error:"Property is required"},{status:400});const db=adminClient(),{data:profile,error}=await db.from("property_profiles").select("id,profile_data").eq("property_id",body.propertyId).maybeSingle();if(error)throw error;const profileData=profile?.profile_data&&typeof profile.profile_data==="object"?profile.profile_data as Record<string,unknown>:{},competitorSet={main:clean(body.competitorSet?.main,4),additional:clean(body.competitorSet?.additional,3),criteria:body.competitorSet?.criteria??{}};const payload:Record<string,unknown>={property_id:body.propertyId,profile_data:{...profileData,competitorSet},verification_status:"NEEDS_REVIEW",updated_by:user.id,updated_at:new Date().toISOString()};if(profile?.id)payload.id=profile.id;const {error:saveError}=await db.from("property_profiles").upsert(payload,{onConflict:"property_id"});if(saveError)throw saveError;return NextResponse.json({ok:true,competitorSet});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not save competitors"},{status:500})}}
