import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";
import { HOTEL_PROFILE_SEEDS } from "../../../profile-seed-data";

export const dynamic="force-dynamic";
const SUPABASE_URL="https://otiiioaazkanroyzvlkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_zMueiaaAsayg8y1fOBazLg_MauoW5hY";
function adminClient(){const key=process.env.SUPABASE_SECRET_KEY;if(!key)throw new Error("SUPABASE_SECRET_KEY is not configured");return createClient(SUPABASE_URL,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function requireMaster(request:NextRequest){const token=(request.headers.get("authorization")??"").replace(/^Bearer /,"");if(!token)return null;const auth=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});const {data:{user}}=await auth.auth.getUser(token);if(!user)return null;const {data}=await adminClient().from("occupancy_user_access").select("role,active").eq("user_id",user.id).maybeSingle();return data?.active&&data.role==="MASTER_ADMIN"?user:null}
function deepFill(existing:unknown,draft:unknown):unknown{if(existing&&draft&&typeof existing==="object"&&typeof draft==="object"&&!Array.isArray(existing)&&!Array.isArray(draft)){const result={...(draft as Record<string,unknown>)};for(const [key,value] of Object.entries(existing as Record<string,unknown>))result[key]=deepFill(value,result[key]);return result}if(Array.isArray(existing)&&existing.length)return existing;return String(existing??"").trim()?existing:draft}
function completion(data:Record<string,unknown>){const values:string[]=[];const visit=(value:unknown)=>{if(Array.isArray(value)){value.forEach(visit);return}if(value&&typeof value==="object"){Object.values(value as Record<string,unknown>).forEach(visit);return}values.push(String(value??"").trim())};visit(data);return Math.min(100,Math.round(values.filter(Boolean).length/160*100))}

export async function POST(request:NextRequest){const user=await requireMaster(request);if(!user)return NextResponse.json({error:"Master Admin access required"},{status:403});try{const db=adminClient();const {data:properties,error}=await db.from("properties").select("id,name,legacy_hotel_code,property_profiles(id,profile_data)");if(error)throw error;let updated=0,sourceCount=0;for(const property of properties??[]){const code=property.legacy_hotel_code??"",seed=HOTEL_PROFILE_SEEDS[code];if(!seed)continue;const profile=property.property_profiles?.[0],merged=deepFill(profile?.profile_data??{},seed.profile) as Record<string,unknown>,percent=completion(merged);const {error:profileError}=await db.from("property_profiles").upsert({id:profile?.id,property_id:property.id,profile_data:merged,completion_percent:percent,verification_status:"NEEDS_REVIEW",marketing_readiness:percent>=80?"READY":percent>=40?"PARTIAL":"NOT_READY",updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:"property_id"});if(profileError)throw profileError;updated++;for(const source of seed.sources){const {data:found}=await db.from("property_profile_sources").select("id").eq("property_id",property.id).eq("source_url",source.url).maybeSingle();if(!found){const {error:sourceError}=await db.from("property_profile_sources").insert({property_id:property.id,source_type:source.type,label:source.label,source_url:source.url,scan_status:"READY",confidence:75,created_by:user.id,last_scanned_at:new Date().toISOString()});if(sourceError)throw sourceError;sourceCount++}}}return NextResponse.json({ok:true,updated,sourceCount});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not import researched profiles"},{status:500})}}
