"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "../supabase";

type Category="OTA"|"YIELD"|"MARKETING"|"REPUTATION";
type Action={id:string;category:Category;priority:string;finding:string;primary_action:string;status:string;affected_from:string|null;affected_to:string|null;properties?:{name?:string;legacy_hotel_code?:string}|null};

const descriptions:Record<Category,string>={OTA:"Channel-manager inventory actions created from remarkable occupancy and rooms-sold changes.",YIELD:"Rate-change recommendations created from occupancy levels, booking pace and significant movements.",MARKETING:"Demand-generation opportunities prepared from weak periods, hotel profiles and market timing.",REPUTATION:"Review intelligence, reply preparation and corrective actions requiring management attention."};

export function ModuleClient({category}:{category:Category}){
 const [actions,setActions]=useState<Action[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 const load=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.from("intelligence_actions").select("id,category,priority,finding,primary_action,status,affected_from,affected_to,properties(name,legacy_hotel_code)").eq("category",category).order("created_at",{ascending:false}).limit(100);if(error)setMessage(error.message);else{setActions((data??[]) as unknown as Action[]);setMessage("")}setLoading(false)},[category]);
 useEffect(()=>{void load()},[load]);
 const counts=useMemo(()=>({open:actions.filter(a=>!["RESOLVED","DISMISSED","EXPIRED"].includes(a.status)).length,critical:actions.filter(a=>a.priority==="CRITICAL"&&!['RESOLVED','DISMISSED'].includes(a.status)).length,review:actions.filter(a=>a.status==="AWAITING_REVIEW").length,completed:actions.filter(a=>["COMPLETED","MONITORING","RESOLVED"].includes(a.status)).length}),[actions]);
 return <div className="intel-page"><section className="intel-intro"><div><h2>{category} management</h2><p>{descriptions[category]}</p></div><button className="intel-primary" onClick={()=>void load()} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></section><section className="intel-kpis"><article className="intel-card orange"><span>OPEN ACTIONS</span><b>{counts.open}</b><small>Active management items</small></article><article className="intel-card urgent"><span>CRITICAL</span><b>{counts.critical}</b><small>Immediate review required</small></article><article className="intel-card purple"><span>AWAITING REVIEW</span><b>{counts.review}</b><small>Prepared for Master</small></article><article className="intel-card teal"><span>COMPLETED</span><b>{counts.completed}</b><small>Completed or monitoring</small></article></section><section className="intel-panel"><header><div><h2>Management queue</h2><p>Evidence, recommendation and current workflow position.</p></div></header>{actions.length?<div className="intel-actions">{actions.map(action=><article className={`intel-action ${action.priority.toLowerCase()}`} key={action.id}><i/><div><b>{action.properties?.name??"Group action"} — {action.finding}</b><small>{action.primary_action}</small></div><span>{action.status.replaceAll("_"," ")}</span></article>)}</div>:<div className="intel-empty"><span>{category.slice(0,2)}</span><h3>{loading?"Loading actions…":"No actions yet"}</h3><p>{message?"Apply the intelligence foundation SQL in Supabase before using this module.":"Scheduled analysis will place evidence-based recommendations here without duplicating active actions."}</p></div>}</section></div>
}
