"use client";

import { useEffect, useState } from "react";
import { supabase } from "../supabase";

type CountState={ota:number;yield:number;marketing:number;reputation:number;properties:number;ready:number};
export function OverviewClient(){
 const [counts,setCounts]=useState<CountState>({ota:0,yield:0,marketing:0,reputation:0,properties:0,ready:0}),[available,setAvailable]=useState(true);
 useEffect(()=>{void (async()=>{const [actions,properties]=await Promise.all([supabase.from("intelligence_actions").select("category,status"),supabase.from("property_profiles").select("completion_percent,marketing_readiness")]);if(actions.error||properties.error){setAvailable(false);return}const open=(actions.data??[]).filter(item=>!["RESOLVED","DISMISSED","EXPIRED"].includes(item.status));setCounts({ota:open.filter(item=>item.category==="OTA").length,yield:open.filter(item=>item.category==="YIELD").length,marketing:open.filter(item=>item.category==="MARKETING").length,reputation:open.filter(item=>item.category==="REPUTATION").length,properties:(properties.data??[]).length,ready:(properties.data??[]).filter(item=>item.marketing_readiness==="READY").length})})()},[]);
 return <div className="intel-page"><section className="intel-intro"><div><h2>Management intelligence overview</h2><p>One decision layer connecting occupancy movements, channel-manager inventory, selling rates, marketing demand and guest reputation.</p></div></section><section className="intel-kpis"><article className="intel-card orange"><span>OTA</span><b>{counts.ota}</b><small>Inventory actions</small></article><article className="intel-card purple"><span>YIELD</span><b>{counts.yield}</b><small>Rate actions</small></article><article className="intel-card teal"><span>MARKETING</span><b>{counts.marketing}</b><small>Demand opportunities</small></article><article className="intel-card urgent"><span>REPUTATION</span><b>{counts.reputation}</b><small>Guest-facing actions</small></article></section><section className="intel-grid"><article className="intel-panel"><header><div><h2>Shared priority feed</h2><p>The most important management decisions across all modules.</p></div></header><div className="intel-empty"><span>AI</span><h3>{available?"No priority actions yet":"Foundation setup required"}</h3><p>{available?"The first scheduled analysis will create evidence-based actions here.":"Apply supabase/intelligence_foundation.sql to activate the new Master-only modules."}</p></div></article><aside className="intel-panel"><header><div><h2>Profile readiness</h2><p>AI-readable hotel intelligence.</p></div></header><div className="intel-kpis" style={{gridTemplateColumns:"1fr 1fr",marginBottom:0}}><article className="intel-card"><span>PROFILES</span><b>{counts.properties}</b><small>Lavendish hotels</small></article><article className="intel-card teal"><span>READY</span><b>{counts.ready}</b><small>Marketing-ready</small></article></div></aside></section></div>
}
