import {createClient} from "@supabase/supabase-js";
import {NextRequest,NextResponse} from "next/server";

export const dynamic="force-dynamic";
const SUPABASE_URL="https://otiiioaazkanroyzvlkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_zMueiaaAsayg8y1fOBazLg_MauoW5hY";
const CATEGORIES=["OTA","YIELD","RESERVATIONS","MARKETING","REPUTATION","OPERATIONS","FINANCE","OTHER"] as const;
const PRIORITIES=["LOW","NORMAL","HIGH","URGENT"] as const;
const STATUSES=["NEW","IN_PROGRESS","DONE"] as const;
function admin(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY??process.env.SUPABASE_SECRET_KEY;if(!key)throw new Error("SUPABASE_SERVICE_ROLE_KEY is not configured");return createClient(SUPABASE_URL,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function accessFor(request:NextRequest){const header=request.headers.get("authorization")??"",token=header.startsWith("Bearer ")?header.slice(7):"";if(!token)return null;const auth=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}),{data:{user}}=await auth.auth.getUser(token);if(!user)return null;const db=admin(),{data}=await db.from("occupancy_user_access").select("role,hotel_codes,page_codes,active").eq("user_id",user.id).maybeSingle();if(!data?.active||!(data.page_codes??[]).some((code:string)=>code==="ALL"||code==="TASKS"))return null;return {...data,user}}
function allowedHotel(access:{role:string;hotel_codes:string[]},code:string|null){return access.role==="MASTER_ADMIN"||access.hotel_codes.includes("ALL")||!code||access.hotel_codes.includes(code)}
export async function GET(request:NextRequest){try{const access=await accessFor(request);if(!access)return NextResponse.json({error:"Tasks access required"},{status:403});const db=admin();let query=db.from("nkh_tasks").select("*").order("status").order("due_date",{ascending:true,nullsFirst:false}).order("created_at",{ascending:false});if(access.role!=="MASTER_ADMIN")query=query.eq("assigned_to",access.user.id);const {data,error}=await query;if(error)throw error;const tasks=(data??[]).filter(task=>allowedHotel(access,task.hotel_code));let users:Array<{id:string;name:string;email:string}>=[];if(access.role==="MASTER_ADMIN"){const [{data:authData,error:authError},{data:rows,error:rowsError}]=await Promise.all([db.auth.admin.listUsers({page:1,perPage:1000}),db.from("occupancy_user_access").select("user_id,role,active")]);if(authError)throw authError;if(rowsError)throw rowsError;const active=new Map((rows??[]).filter(row=>row.active).map(row=>[row.user_id,row.role]));users=authData.users.filter(user=>active.has(user.id)&&active.get(user.id)!=="MASTER_ADMIN").map(user=>({id:user.id,name:String(user.user_metadata?.full_name??user.email?.split("@")[0]??"Staff"),email:user.email??""})).sort((a,b)=>a.name.localeCompare(b.name))}return NextResponse.json({tasks,users,isMaster:access.role==="MASTER_ADMIN"})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not load tasks"},{status:500})}}
export async function POST(request:NextRequest){try{const access=await accessFor(request);if(!access||access.role!=="MASTER_ADMIN")return NextResponse.json({error:"Master Admin access required"},{status:403});const body=await request.json() as Record<string,unknown>,title=String(body.title??"").trim(),category=String(body.category??""),priority=String(body.priority??""),assignedTo=String(body.assignedTo??""),hotelCode=String(body.hotelCode??"").trim()||null,dueDate=String(body.dueDate??"").trim()||null;if(title.length<3||!assignedTo||!CATEGORIES.includes(category as typeof CATEGORIES[number])||!PRIORITIES.includes(priority as typeof PRIORITIES[number]))return NextResponse.json({error:"Complete the task title, assignee, category and priority"},{status:400});const db=admin(),{data:user}=await db.auth.admin.getUserById(assignedTo);if(!user.user)return NextResponse.json({error:"Assigned user was not found"},{status:400});const assignedName=String(user.user.user_metadata?.full_name??user.user.email?.split("@")[0]??"Staff"),now=new Date().toISOString(),{data,error}=await db.from("nkh_tasks").insert({title,description:String(body.description??"").trim(),hotel_code:hotelCode,category,priority,status:"NEW",assigned_to:assignedTo,assigned_name:assignedName,due_date:dueDate,remarks:"",created_by:access.user.id,created_at:now,updated_at:now}).select("*").single();if(error)throw error;return NextResponse.json({task:data},{status:201})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not create task"},{status:500})}}
export async function PATCH(request:NextRequest){try{const access=await accessFor(request);if(!access)return NextResponse.json({error:"Tasks access required"},{status:403});const body=await request.json() as Record<string,unknown>,id=String(body.id??""),status=String(body.status??"");if(!id||!STATUSES.includes(status as typeof STATUSES[number]))return NextResponse.json({error:"Valid task and status are required"},{status:400});const db=admin(),{data:task,error:readError}=await db.from("nkh_tasks").select("id,assigned_to,hotel_code").eq("id",id).maybeSingle();if(readError||!task)return NextResponse.json({error:"Task not found"},{status:404});if(access.role!=="MASTER_ADMIN"&&task.assigned_to!==access.user.id)return NextResponse.json({error:"This task is not assigned to you"},{status:403});if(!allowedHotel(access,task.hotel_code))return NextResponse.json({error:"Hotel access denied"},{status:403});const now=new Date().toISOString(),{data,error}=await db.from("nkh_tasks").update({status,remarks:String(body.remarks??"").trim(),completed_at:status==="DONE"?now:null,updated_at:now}).eq("id",id).select("*").single();if(error)throw error;return NextResponse.json({task:data})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not update task"},{status:500})}}