"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { useAuth } from "../../auth-provider";

type Result={hotel:string;status:string;rate:number|null;currency:string;availableCheckIn?:string;daysShifted?:number;source?:string;sourceUrl?:string};
type Analysis={checkedAt?:string;ourRate?:number|null;marketMedian?:number|null;suggestedRate?:number|null;occupancy?:number|null;confidence?:string;summary?:string;reason?:string;guide?:string;results?:Result[]};
type Hotel={id:string;name:string;code:string|null;location:string|null;mainCompetitors:string[];analysis:Analysis|null;previousAnalysis:Analysis|null};

function money(rate:number|null|undefined,currency="USD"){return rate==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:0}).format(rate)}
function previousRate(previous:Analysis|null,name:string){return previous?.results?.find(item=>item.hotel.trim().toLowerCase()===name.trim().toLowerCase())?.rate??null}
function change(current:number|null,previous:number|null){if(current==null||previous==null)return null;return current-previous}

export function CompSetClient(){
 const {session,access}=useAuth(),[hotels,setHotels]=useState<Hotel[]>([]),[selected,setSelected]=useState(""),[loading,setLoading]=useState(true),[running,setRunning]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{if(!session)return;setLoading(true);try{const response=await fetch("/api/comp-set",{headers:{Authorization:`Bearer ${session.access_token}`},cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error??"Could not load Comp Set");setHotels(data.hotels??[]);setSelected(current=>data.hotels?.some((item:Hotel)=>item.id===current)?current:(data.hotels?.[0]?.id??""));setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Could not load Comp Set")}finally{setLoading(false)}},[session]);
 useEffect(()=>{void load()},[load]);
 async function runSelected(){if(!session||access?.role!=="MASTER_ADMIN"||running||!selected)return;const selectedHotel=hotels.find(item=>item.id===selected);setRunning(true);setError("");setNotice(`Checking ${selectedHotel?.name??"selected hotel"}…`);try{const response=await fetch("/api/comp-set/check",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({propertyId:selected})}),data=await response.json();if(!response.ok)throw new Error(data.error??"Could not run rate check");const result=data.results?.[0];if(!result?.ok)throw new Error(result?.message??"Rate check did not complete");setNotice(`${selectedHotel?.name??"Hotel"} checked successfully using ${result.competitorCount??0} competitors.`);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Could not run rate check");setNotice("")}finally{setRunning(false)}}
 const hotel=useMemo(()=>hotels.find(item=>item.id===selected)??hotels[0],[hotels,selected]),analysis=hotel?.analysis,previous=hotel?.previousAnalysis,mainNames=new Set((hotel?.mainCompetitors??[]).map(name=>name.trim().toLowerCase())),results=(analysis?.results??[]).filter(item=>mainNames.has(item.hotel.trim().toLowerCase())).slice(0,4),changed=results.filter(item=>change(item.rate,previousRate(previous,item.hotel))!==0&&change(item.rate,previousRate(previous,item.hotel))!==null).length;
 return <div className="intel-page comp-page">
  <section className="comp-command"><div><small>READ-ONLY RATE MONITOR</small><h2>Competitive rate position</h2><p>The four prioritized Main competitors, their latest rates, movements and revenue guidance.</p></div><div className="comp-controls"><label><span>HOTEL</span><select value={selected} onChange={event=>setSelected(event.target.value)}>{hotels.map(item=><option value={item.id} key={item.id}>{item.code} · {item.name}</option>)}</select></label>{access?.role==="MASTER_ADMIN"&&<button className="comp-run-all" disabled={running||!selected} onClick={()=>void runSelected()}>{running?"Checking selected hotel…":"Run Rate Check"}</button>}</div></section>
  {notice&&<div className="comp-notice">{notice}</div>}
  <section className="comp-schedule"><div><span>Automatic checks</span><b>06:00 · 11:00 · 15:00</b><small>Sri Lanka time · no competitor editing on this page</small></div><div><span>Last checked</span><b>{analysis?.checkedAt?new Date(analysis.checkedAt).toLocaleString():"Waiting for first run"}</b><small>{changed} rate {changed===1?"change":"changes"} in latest comparison</small></div></section>
  {error&&<div className="comp-empty error">{error}</div>}{loading&&<div className="comp-empty">Loading rate intelligence…</div>}
  {!loading&&!analysis&&<div className="comp-empty"><b>No completed check yet</b><span>The next scheduled run will populate this hotel automatically.</span></div>}
  {analysis&&<><section className="comp-kpis"><article><span>OUR LIVE RATE</span><b>{money(analysis.ourRate)}</b><small>Public rate found automatically</small></article><article><span>MARKET MEDIAN</span><b>{money(analysis.marketMedian)}</b><small>Comparable verified rates</small></article><article className="accent"><span>SUGGESTED RATE</span><b>{money(analysis.suggestedRate)}</b><small>{analysis.confidence??"LOW"} confidence</small></article><article><span>OCCUPANCY</span><b>{analysis.occupancy==null?"—":`${analysis.occupancy}%`}</b><small>Selected stay date</small></article></section>
  <section className="comp-guidance"><div><small>SMART RECOMMENDATION</small><h3>{analysis.guide??"Review the latest market position."}</h3><p>{analysis.reason??analysis.summary}</p></div></section>
  <section className="comp-table"><header><span>Competitor</span><span>Previous</span><span>Current</span><span>Movement</span><span>Availability</span></header>{results.map(item=>{const prior=previousRate(previous,item.hotel),delta=change(item.rate,prior),direction=delta==null?"new":delta>0?"up":delta<0?"down":"hold";return <article key={item.hotel}><div><b>{item.hotel}</b><small>{item.source??"Google Hotels"}</small></div><span>{money(prior,item.currency)}</span><strong>{money(item.rate,item.currency)}</strong><span className={direction}>{delta==null?"NEW":delta===0?"—":`${delta>0?"↑":"↓"} ${money(Math.abs(delta),item.currency)}`}</span><span className={item.rate==null?"missing":"available"}>{item.rate==null?"No rate":item.daysShifted?`+${item.daysShifted} day fallback`:"Requested date"}</span></article>})}</section></>}
 </div>
}
