"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { useAuth } from "../../auth-provider";

type Result={hotel:string;status:string;rate:number|null;currency:string;availableCheckIn?:string;daysShifted?:number;source?:string;sourceUrl?:string};
type Analysis={checkedAt?:string;ourRate?:number|null;marketMedian?:number|null;suggestedRate?:number|null;occupancy?:number|null;confidence?:string;summary?:string;reason?:string;guide?:string;results?:Result[]};
type Hotel={id:string;name:string;code:string|null;location:string|null;mainCompetitors:string[];analysis:Analysis|null;previousAnalysis:Analysis|null};

function money(rate:number|null|undefined,currency="USD"){return rate==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:0}).format(rate)}
function previousRate(previous:Analysis|null,name:string){return previous?.results?.find(item=>item.hotel.trim().toLowerCase()===name.trim().toLowerCase())?.rate??null}
function change(current:number|null,previous:number|null){if(current==null||previous==null)return null;return current-previous}

export function CompSetClient(){
 const {session,access}=useAuth(),[hotels,setHotels]=useState<Hotel[]>([]),[selected,setSelected]=useState(""),[loading,setLoading]=useState(true),[running,setRunning]=useState(false),[savingRates,setSavingRates]=useState(false),[editingRates,setEditingRates]=useState(false),[manualOurRate,setManualOurRate]=useState(""),[manualRates,setManualRates]=useState<Record<string,string>>({}),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{if(!session)return;setLoading(true);try{const response=await fetch("/api/comp-set",{headers:{Authorization:`Bearer ${session.access_token}`},cache:"no-store"}),data=await response.json();if(!response.ok)throw new Error(data.error??"Could not load Comp Set");setHotels(data.hotels??[]);setSelected(current=>data.hotels?.some((item:Hotel)=>item.id===current)?current:(data.hotels?.[0]?.id??""));setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Could not load Comp Set")}finally{setLoading(false)}},[session]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{setEditingRates(false);setManualOurRate("");setManualRates({});setNotice("")},[selected]);
 async function runSelected(){if(!session||access?.role!=="MASTER_ADMIN"||running||!selected)return;const selectedHotel=hotels.find(item=>item.id===selected);setRunning(true);setError("");setNotice(`Checking ${selectedHotel?.name??"selected hotel"}…`);try{const response=await fetch("/api/comp-set/check",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({propertyId:selected})}),data=await response.json();if(!response.ok)throw new Error(data.error??"Could not run rate check");const result=data.results?.[0];if(!result?.ok)throw new Error(result?.message??"Rate check did not complete");setNotice(result.message??`${selectedHotel?.name??"Hotel"} checked successfully using ${result.competitorCount??0} competitors.`);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Could not run rate check");setNotice("")}finally{setRunning(false)}}
 async function saveManualRates(){if(!session||!selected||savingRates)return;const rates=Object.fromEntries(Object.entries(manualRates).filter(([,value])=>value.trim()&&Number(value)>0).map(([name,value])=>[name,Number(value)])),ourRate=manualOurRate.trim()&&Number(manualOurRate)>0?Number(manualOurRate):undefined;if(ourRate==null&&!Object.keys(rates).length){setError("Enter at least one rate.");return}setSavingRates(true);setError("");try{const response=await fetch("/api/comp-set",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({propertyId:selected,ourRate,rates})}),data=await response.json();if(!response.ok)throw new Error(data.error??"Could not save rates");setNotice("Rates saved and recommendation updated.");setEditingRates(false);setManualOurRate("");setManualRates({});await load()}catch(reason){setError(reason instanceof Error?reason.message:"Could not save rates")}finally{setSavingRates(false)}}
 const hotel=useMemo(()=>hotels.find(item=>item.id===selected)??hotels[0],[hotels,selected]),analysis=hotel?.analysis,previous=hotel?.previousAnalysis,results=(hotel?.mainCompetitors??[]).slice(0,4).map(name=>analysis?.results?.find(item=>item.hotel.trim().toLowerCase()===name.trim().toLowerCase())??{hotel:name,status:"NOT_VERIFIED",rate:null,currency:"USD"}),changed=results.filter(item=>change(item.rate,previousRate(previous,item.hotel))!==0&&change(item.rate,previousRate(previous,item.hotel))!==null).length;
 return <div className="intel-page comp-page">
  <section className="comp-command"><div><h2>Rate position</h2></div><div className="comp-controls"><label><span>HOTEL</span><select value={selected} onChange={event=>setSelected(event.target.value)}>{hotels.map(item=><option value={item.id} key={item.id}>{item.code} · {item.name}</option>)}</select></label><button className="comp-edit-rates" disabled={!selected} onClick={()=>{setEditingRates(true);setManualOurRate(analysis?.ourRate?String(analysis.ourRate):"");setManualRates(Object.fromEntries(results.filter(item=>item.rate!=null).map(item=>[item.hotel,String(item.rate)])))}}>Edit Rates</button>{access?.role==="MASTER_ADMIN"&&<button className="comp-run-all" disabled={running||!selected} onClick={()=>void runSelected()}>{running?"Checking selected hotel…":"Run Rate Check"}</button>}</div></section>
  {notice&&<div className="comp-notice">{notice}</div>}
  <section className="comp-schedule"><div><span>SCHEDULE</span><b>06:00 · 11:00 · 15:00</b></div><div><span>LAST UPDATE</span><b>{analysis?.checkedAt?new Date(analysis.checkedAt).toLocaleString():"—"}</b></div><div><span>CHANGES</span><b>{changed}</b></div></section>
  {error&&<div className="comp-empty error">{error}</div>}{loading&&<div className="comp-empty">Loading rate intelligence…</div>}
  {!loading&&editingRates&&<section className="comp-rate-editor"><header><div><small>MANUAL RATE UPDATE</small><h3>Edit current rates</h3></div><button type="button" onClick={()=>setEditingRates(false)}>Cancel</button></header><div className="comp-editor-grid"><label className="our-rate"><span>OUR HOTEL</span><b>{hotel?.name}</b><input autoFocus type="number" min="1" step="1" value={manualOurRate} onChange={event=>setManualOurRate(event.target.value)} placeholder="Enter our rate"/></label>{(hotel?.mainCompetitors??[]).slice(0,4).map(name=><label key={name}><span>COMPETITOR</span><b>{name}</b><input type="number" min="1" step="1" value={manualRates[name]??""} onChange={event=>setManualRates(current=>({...current,[name]:event.target.value}))} placeholder="Enter rate"/></label>)}</div><footer><span>Enter only the rates you want to update.</span><button className="comp-save-rates" disabled={savingRates} onClick={()=>void saveManualRates()}>{savingRates?"Saving…":"Save Rates"}</button></footer></section>}
  {!loading&&!analysis&&!editingRates&&<div className="comp-empty"><b>No rates saved yet</b><span>Use Run Rate Check or Edit Rates.</span></div>}
  {analysis&&<><section className="comp-kpis"><article><span>OUR RATE</span><b>{money(analysis.ourRate)}</b></article><article><span>MARKET MEDIAN</span><b>{money(analysis.marketMedian)}</b></article><article className="accent"><span>SUGGESTED RATE</span><b>{money(analysis.suggestedRate)}</b><small>{analysis.confidence??"LOW"}</small></article><article><span>OCCUPANCY</span><b>{analysis.occupancy==null?"—":`${analysis.occupancy}%`}</b></article></section>
  <section className="comp-guidance"><div><small>RATE GUIDE</small><h3>{analysis.guide??"Review the latest market position."}</h3><p>{analysis.reason??analysis.summary}</p></div></section>
  <section className="comp-table"><header><span>Competitor</span><span>Previous</span><span>Current</span><span>Movement</span><span>Availability</span></header>{results.map(item=>{const prior=previousRate(previous,item.hotel),delta=change(item.rate,prior),direction=delta==null?"new":delta>0?"up":delta<0?"down":"hold";return <article key={item.hotel}><div><b>{item.hotel}</b><small>{item.source??"Google Hotels"}</small></div><span>{money(prior,item.currency)}</span><div className="comp-rate-cell"><strong>{money(item.rate,item.currency)}</strong></div><span className={direction}>{delta==null?"NEW":delta===0?"—":`${delta>0?"↑":"↓"} ${money(Math.abs(delta),item.currency)}`}</span><span className={item.rate==null?"missing":"available"}>{item.rate==null?"No rate":item.status==="CACHED"?"Last saved rate":item.daysShifted?`+${item.daysShifted} day fallback`:"Requested date"}</span></article>})}</section></>}
 </div>
}
